### ISSUE TITLE
APK DOSNT ASK PERMISSIONS

### ISSUE THREAD

**Issue by devilmen80** [jbreed/apkwash#11]
Hello all is generated but when I install infected APK on my phone it doesn'ask any permission so many modules of meterpreter don't work.

Have you solution??

Thanks in advance.

**Comment by HeYiKunclass** [comment]
I have the same problem

**Comment by jbreed** [comment]
@devilmen80 @HeYiKunclass 

This project is no longer supported, but if a pull request is submitted to correct these I'll merge it in.

Thanks
